### ISSUE TITLE
HeroChatBridge Support

### ISSUE THREAD

**Issue by HeroCC** [minecrafter/Shortify#18]
Is there any way for you to integrate support with HeroChat, and possibly other chat managers? My server uses HeroChat for formatting and channels, and shortify looks like the best link shortener. Thanks!

EDIT: My problem was HeroChatBridge being not compatible. Any chance of a fix?

**Comment by dewick** [comment]
I use Shortify with Herochat an it works flawlessly. What exactly is your issue?

**Comment by dewick** [comment]
I use Shortify with Herochat an it works flawlessly. What exactly is your issue?

**Comment by dewick** [comment]
I use Shortify with Herochat an it works flawlessly. What exactly is your issue?

**Comment by Marqueue** [comment]
Shortify should play well with other plugins doing chat. My suggestion is to try it and see if it works. If it doesn't, I am glad to fix any issues.

**Comment by HeroCC** [comment]
Ok, I think I found the problem. I use a plugin called [HeroChatBridge](http://www.spigotmc.org/resources/herochatbungeebridge-bungee.189/) which allows me to have cross-server chat via HeroChat and BungeeCord, and it doesn't seem to be compatible. Is there any way you can add support for it? Thanks!

**Comment by minecrafter** [comment]
I can't add support for the bridge but you can try the BungeeCord plugin (which is the same JAR as the Bukkit version).

**Comment by HeroCC** [comment]
I used both, same thing.

**Comment by minecrafter** [comment]
Please raise the issue with the author of HeroChatBridge.
